config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  resources :article_categories do
    resources :articles
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  paginates_per 2

  has_many :comments, dependent: :destroy
  belongs_to :category, foreign_key: :article_category_id

  validates :title, presence: true,
                    length: { minimum: 5 }
  validates :author_name, presence: true
  validates :state, inclusion: { in: %w(draft published),
    # message: t('state_validates', value: value) }
    message: "%{value} is not a valid state" }
end

app/models/article/category.rb
class Article::Category < ApplicationRecord
  has_many :article
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, :email => true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/article_categories_controller.rb
class ArticleCategoriesController < ApplicationController
  def index
    # @categories = Article::Category.all
    @q = Article::Category.ransack(params[:q])
    @categories = @q.result(distinct: true).page(params[:page])
  end

  def show
    @category = Article::Category.find(params[:id])
  end

  def new
    @category = Article::Category.new
  end

  def edit
    @category = Article::Category.find(params[:id])
  end

  def create
    @category = Article::Category.new(category_params)

    if @category.save
      redirect_to article_categories_path
    else
      render 'new'
    end
  end

  def update
    @category = Article::Category.find(params[:id])

    if @category.update(category_params)
      redirect_to article_categories_path
    else
      # binding.irb
      render 'edit'
    end
  end

  def destroy
    @category = Article::Category.find(params[:id])
    @category.destroy

    redirect_to article_categories_path
  end

  def category_params
    params.require(:article_category).permit(:name, :slug)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # http_basic_authenticate_with name: "test", password: "test", except: [:index, :show]

  def index
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true).page(params[:page])
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      # binding.irb
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  def article_params
    params.require(:article).permit(:title, :text, :author_name, :state, :article_category_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # http_basic_authenticate_with name: "test", password: "test", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/article_categories/_form.html.slim
.container
 p
    = simple_form_for(@category, html: { class: 'form-horisontal' }) do |form|
      = form.input :name
      = form.input :slug
      = form.button :submit

app/views/article_categories/edit.html.slim
.container
  h1
    = t('.caption')
  = render 'form'
  = link_to t('back'), article_categories_path

app/views/article_categories/index.html.slim
.container
  h1
    = t('.caption')

  = link_to t('.new_category'), new_article_category_path

  br

  table
    tr
      th= sort_link(@q, :name)
      th= sort_link(@q, :slug)
      th[colspan="4"]
    - @categories.each do |category|
      tr
        td= category.name
        td= category.slug
        td= link_to t(:show), article_category_path(category)
        td= link_to t(:edit), edit_article_category_path(category)
        td= link_to t(:destroy), article_category_path(category), method: :delete, data: { confirm: t('confirm') }

  br
  = simple_form_for @q, url: article_categories_path, html: { method: 'get' } do |f|
    = f.search_field :name_cont
    = f.search_field :slug_cont
    = f.submit

  br
  = paginate @categories

app/views/article_categories/new.html.slim
.container
  h1
    = t('.caption')
  = render 'form'
  = link_to t('back'), article_categories_path

app/views/article_categories/show.html.slim
.container
  h1
    = t('.caption')
  p
    strong
      = t('.name')
      | :
    = @category.name
  p
    strong
      = t('.slug')
      | :
    = @category.slug
  = link_to t('edit'), edit_article_category_path(@category)
  | |
  = link_to t('back'), article_categories_path

app/views/articles/_form.html.slim
.container
 p
    = simple_form_for(@article, html: { class: 'form-horisontal' }) do |form|
      = form.input :title
      = form.input :text
      = form.input :author_name
      = form.input :state, as: :select, collection: ['draft', 'published'], selected: 'draft'
      = form.association :category
      = form.button :submit

app/views/articles/edit.html.slim
.container
  h1
    = t('.caption')
  = render 'form'
  = link_to t('back'), articles_path

app/views/articles/index.html.slim
.container
  h1
    = t('.caption')

  = link_to t('.new_article'), new_article_path

  br

  table
    tr
      th= sort_link(@q, :title)
      th= sort_link(@q, :text)
      th= sort_link(@q, :author)
      th= sort_link(@q, :state)
      th[colspan="4"]
    - @articles.each do |article|
      tr
        td= article.title
        td= article.text
        td= article.author_name
        td= article.state
        td= link_to t(:show), article_path(article)
        td= link_to t(:edit), edit_article_path(article)
        td= link_to t(:destroy), article_path(article), method: :delete, data: { confirm: t('confirm') }

  br
  = simple_form_for @q, url: articles_path, html: { method: 'get' } do |f|
    = f.search_field :title_cont
    = f.select :state_cont, options_for_select([[t('.draft'), 'draft'], [t('.published'), 'published']], @q.state_cont)
    = f.submit

  br
  = paginate @articles

app/views/articles/new.html.slim
.container
  h1
    = t('.caption')
  = render 'form'
  = link_to t('back'), articles_path

app/views/articles/show.html.slim
.container
  h1
    = t('.caption')
  p
    strong
      = t('.title')
      | :
    = @article.title
  p
    strong
      = t('.text')
      | :
    = @article.text
  p
    strong
      = t('.author')
      | :
    = @article.author_name
  p
    strong
      = t('.status')
      | :
    = @article.state

  h2= t('.comments')
  = render @article.comments

  h4= t('.add_comment')
  = render 'comments/form'
  = link_to t('edit'), edit_article_path(@article)
  | |
  = link_to t('back'), articles_path

app/views/comments/_comment.html.slim
p
  strong
    = t('.commenter')
  | :
  = comment.commenter
p
  strong
    = t('.comment')
  | :
  = comment.body
p
  = link_to t('.destroy_comment'), [comment.article, comment], method: :delete, data: { confirm: t('confirm') }

app/views/comments/_form.html.slim
.container
 p
    = simple_form_for [ @article, @article.comments.build ] do |form|
      = form.input :commenter
      = form.input :body
      = form.button :submit

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Blog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/users/_form.html.slim
= form_with(model: user, local: true) do |form|
  - if user.errors.any?
    #error_explanation
      h2
        = pluralize(user.errors.count, "error")
        | prohibited this user from being saved:
      ul
        - user.errors.full_messages.each do |message|
          li= message
  .field
    = form.label :first_name
    = form.text_field :first_name, id: :user_first_name
  .field
    = form.label :last_name
    = form.text_field :last_name, id: :user_last_name
  .field
    = form.label :email
    = form.text_field :email, id: :user_email
  .actions
    = form.submit

app/views/users/edit.html.slim
h1 Editing User
= render 'form', user: @user
= link_to 'Show', @user
| \
= link_to 'Back', users_path

app/views/users/index.html.slim
p#notice= notice
h1 Users
table
  thead
    tr
      th First name
      th Last name
      th Email
      th colspan="3"
  tbody
    - @users.each do |user|
      tr
        td= user.first_name
        td= user.last_name
        td= user.email
        td= link_to 'Show', user
        td= link_to 'Edit', edit_user_path(user)
        td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
br/
= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice= notice
p
  strong First name:
  = @user.first_name
p
  strong Last name:
  = @user.last_name
p
  strong Email:
  = @user.email
= link_to 'Edit', edit_user_path(@user)
| \
= link_to 'Back', users_path

app/views/welcome/index.html.slim
h1 Hello, Rails!
= link_to 'My Blog', controller: 'articles'